theme: jekyll-theme-minimal
description: In this blog you will read about the journey of a guy who dreams to change something in the world. This blog mostly is about programming stuff, an awesome web design related project called wooble.io and some personal thoughts.
title: Slals blog
